theme: jekyll-theme-minimal

title: Portfolio
description: >
  <strong>Software Engineer 路 Game Developer</strong><br/>
  <nav class="side-nav">
    <a href="#about">About / CV</a> 路
    <a href="#itchio">Itch.io Games</a> 路
    <a href="#github">GitHub Projects</a>
  </nav>
  <a href="mailto:xaviflores1@gmail.com">xaviflores1@gmail.com</a> 路 Barcelona, Spain

logo: /assets/avatar.png

github_username:
